name: Run custom action
on:
  push:
    branches: [main]
    paths: [/hello-world-docker-action]
  workflow_run:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@danieldavidjp'

      - name: Output time in container
        run: echo "The last time was ${{ step.hello-action.outpus.time }} when the action say hello"
      
